# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Decorator
version:      1.4
version_from: lib/Text/Decorator.pm
installdirs:  site
requires:
    Template:                      0
    UNIVERSAL::require:            0
    URI::Find:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
